### ISSUE TITLE
Print Statement for total requests

### ISSUE THREAD

**Issue by laurencc1112** [412G5/Project3#1]
The print statement for total requests prints a million times. I understand the issue to be that it is part of the function above it, however, whenever I move it out of said function by taking it back a tab it doesn't print. That, or I'm not waiting long enough for it to.

**Comment by laurencc1112** [comment]
Also- I wrote the code to find the total number of requests by assuming that each line was a 'request'. Each line starts with either "local" or "remote" so it is counting the occurrence of those words. There is definitely a more streamlined way to do this so I am fine if it gets deleted

**Comment by hnokes11** [comment]
We have two branches in the works that address this concern. We shouldn't have to worry about this anymore!
